In [1]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# ------------------------------------------
# desabilita warnings
# ------------------------------------------
import warnings
warnings.filterwarnings('ignore')

In [3]:
# ------------------------------------------
# bibliotecas principais
# ------------------------------------------
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [4]:
# ------------------------------------------
# DATABASE: DF-CONSOLIDADO
#
# features dropadas de inicio : ID, cidade
# ------------------------------------------
df = pd.read_csv("/content/drive/Shareddrives/grupo4-rappi-hour/bases-rappi/df-consolidado.csv")
df.drop(["Unnamed: 0", "ID", "CIDADE"], axis=1, inplace=True)
print(f"Total de linhas: {df.shape[0]}")
df.info()

Total de linhas: 159576
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159576 entries, 0 to 159575
Data columns (total 47 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   GENERO                          159576 non-null  object 
 1   DATA_NASCIMENTO                 159576 non-null  float64
 2   IS_ACTIVE                       159576 non-null  object 
 3   TRANSPORTE                      159576 non-null  object 
 4   AUTO_ACEITE                     140510 non-null  object 
 5   COUNT_ORDERS_LAST_7D            159576 non-null  float64
 6   COUNT_ORDERS_LAST_30D           159576 non-null  float64
 7   COUNT_ORDERS_CANCELED_LAST_7D   159576 non-null  float64
 8   COUNT_ORDERS_CANCELED_LAST_30D  159576 non-null  float64
 9   GORJETA                         159576 non-null  float64
 10  PRIMEIRO_PEDIDO                 140510 non-null  object 
 11  ULTIMO_PEDIDO                   140510 non-null  objec

In [5]:
# ------------------------------------------
# TARGET : CHECAGEM DE INTEGRIDADE
# exibe lista de ocorrencias das variaveis
# qtd de ocorrencia de cada uma das categorias
# ------------------------------------------
print(df["IS_ACTIVE"].unique())
df["IS_ACTIVE"].value_counts(normalize=True)

['True' 'False' 'Quasi' False]


Quasi    0.633805
True     0.245939
False    0.075951
False    0.044305
Name: IS_ACTIVE, dtype: float64

In [6]:
# ------------------------------------------
# substitui False (bool) por False (string)
# ------------------------------------------
df["IS_ACTIVE"].replace({ False: "False"}, inplace=True)

In [7]:
# ------------------------------------------
# substitui dados categoricos por numericos
# ------------------------------------------
df["IS_ACTIVE"].replace({
    "False": 0,
    "True": 1,
    "Quasi": 2
}, inplace=True)

In [8]:
# ------------------------------------------
# CHECAGEM DO TRATAMENTO DO TARGET
# ------------------------------------------
print(df["IS_ACTIVE"].unique())
df["IS_ACTIVE"].value_counts(normalize=True)

[1 0 2]


2    0.633805
1    0.245939
0    0.120256
Name: IS_ACTIVE, dtype: float64

In [9]:
# ------------------------------------------
# FEATURE : GENERO
# exibe lista de ocorrencias das variaveis
# qtd de ocorrencia de cada uma das categorias
# ------------------------------------------
print(df["GENERO"].unique())
df["GENERO"].value_counts(normalize=True)

['M' 'F' 'O']


M    0.877124
F    0.122750
O    0.000125
Name: GENERO, dtype: float64

In [10]:
# ------------------------------------------
# substituicao de dados categoricos por numericos
# ------------------------------------------
df["GENERO"].replace({'M':0, 'F':1, "O": 0}, inplace=True)

In [11]:
# ------------------------------------------
# CHECAGEM DO TRATAMENTO DA FEATURE
# ------------------------------------------
print(df["GENERO"].unique())
df["GENERO"].value_counts(normalize=True)

[0 1]


0    0.87725
1    0.12275
Name: GENERO, dtype: float64

In [12]:
# ------------------------------------------
# FEATURE : DATA_NASCIMENTO
# exibe lista de ocorrencias das variaveis
# qtd de ocorrencia de cada uma das categorias
#
# existencia de dados absurdos: 1505, 1371, 3199, etc
# ------------------------------------------
df["DATA_NASCIMENTO"].unique()

array([1988., 1998., 1994., 1993., 2004., 1997., 1978., 1995., 1992.,
       1983., 1979., 1991., 1973., 1984., 1982., 1985., 1964., 1965.,
       2003., 1996., 2000., 2001., 1999., 1981., 1989., 1980., 1959.,
       1974., 1975., 1972., 1963., 1976., 1987., 1990., 2002., 1950.,
       1952., 1966., 1977., 1969., 1986., 1971., 1961., 1970., 1951.,
       1967., 1968., 1955., 1960., 1962., 1957., 1945., 1958., 1932.,
       1954., 1953., 1956., 1905., 1929., 1940., 1948., 1949., 1914.,
       1909., 1947., 1944., 1908., 1902., 1927., 1943., 1939., 1904.,
       1936., 1942., 1938., 1921., 1906., 1903., 1907., 1919., 2022.,
       1946., 2021., 1916., 1937., 1935., 1933., 1924., 1900., 1930.,
       1922., 1901., 1915., 1926., 2020., 2010., 2016., 2009., 1363.,
       1505., 2018.,  199., 2007., 2008., 1739., 2015., 1590., 2014.,
       2012., 2017., 2006., 2986., 2011., 2195., 2997., 1371., 2019.,
       3199., 2013., 2198.,  195., 1081., 1928., 1198.])

In [13]:
# ------------------------------------------
# 80% das observacoes estao situadas entre os anos de 1983 e 2002
# ------------------------------------------
nascimentos = df["DATA_NASCIMENTO"].value_counts(normalize=True).nlargest(n=20).cumsum()
print(f"Maior ano de nascimento: {nascimentos.index.max()}")
print(f"Menor ano de nascimento: {nascimentos.index.min()}")
nascimentos

Maior ano de nascimento: 2002.0
Menor ano de nascimento: 1983.0


1990.0    0.150662
1999.0    0.195982
1997.0    0.240124
2000.0    0.283182
1998.0    0.326227
1996.0    0.369266
1995.0    0.410751
1994.0    0.451371
1993.0    0.489040
2001.0    0.524133
1992.0    0.557521
1991.0    0.590026
1989.0    0.620826
2002.0    0.650392
1988.0    0.678818
1987.0    0.706804
1986.0    0.732911
1985.0    0.757883
1984.0    0.780249
1983.0    0.801593
Name: DATA_NASCIMENTO, dtype: float64

In [14]:
# ------------------------------------------
# substituicao de registros absurdos por limites maximos e minimos de idade
# max: 60 anos
# min: 18 anos
# ------------------------------------------
from datetime import date

current_year = date.today().year

df['DATA_NASCIMENTO'] = np.where(df['DATA_NASCIMENTO'].lt(current_year - 60), current_year - 60, df['DATA_NASCIMENTO'])
df['DATA_NASCIMENTO'] = np.where(df['DATA_NASCIMENTO'].gt(current_year - 18), current_year - 18, df['DATA_NASCIMENTO'])
df["DATA_NASCIMENTO"].unique()

array([1988., 1998., 1994., 1993., 2004., 1997., 1978., 1995., 1992.,
       1983., 1979., 1991., 1973., 1984., 1982., 1985., 1964., 1965.,
       2003., 1996., 2000., 2001., 1999., 1981., 1989., 1980., 1962.,
       1974., 1975., 1972., 1963., 1976., 1987., 1990., 2002., 1966.,
       1977., 1969., 1986., 1971., 1970., 1967., 1968.])

In [15]:
# ------------------------------------------
# CHECAGEM DO TRATAMENTO DA FEATURE
# ------------------------------------------
print(df["DATA_NASCIMENTO"].unique())
df["DATA_NASCIMENTO"].value_counts(normalize=True)

[1988. 1998. 1994. 1993. 2004. 1997. 1978. 1995. 1992. 1983. 1979. 1991.
 1973. 1984. 1982. 1985. 1964. 1965. 2003. 1996. 2000. 2001. 1999. 1981.
 1989. 1980. 1962. 1974. 1975. 1972. 1963. 1976. 1987. 1990. 2002. 1966.
 1977. 1969. 1986. 1971. 1970. 1967. 1968.]


1990.0    0.150662
1999.0    0.045320
1997.0    0.044142
2000.0    0.043058
1998.0    0.043045
1996.0    0.043039
1995.0    0.041485
1994.0    0.040620
1993.0    0.037669
2001.0    0.035093
1992.0    0.033388
1991.0    0.032505
1989.0    0.030800
2002.0    0.029566
1988.0    0.028425
1987.0    0.027987
1986.0    0.026107
1985.0    0.024972
1984.0    0.022366
1983.0    0.021344
1982.0    0.021093
2003.0    0.020047
1981.0    0.018919
1980.0    0.016387
1979.0    0.014470
1978.0    0.012308
1977.0    0.010923
1976.0    0.010002
1975.0    0.008867
1962.0    0.008798
1974.0    0.007620
1973.0    0.006881
1972.0    0.006317
1971.0    0.005634
2004.0    0.005508
1970.0    0.005007
1969.0    0.004011
1968.0    0.003378
1967.0    0.003039
1966.0    0.002663
1965.0    0.002419
1964.0    0.002093
1963.0    0.002024
Name: DATA_NASCIMENTO, dtype: float64

In [16]:
# ------------------------------------------
# FEATURE : TRANSPORTE
# exibe lista de ocorrencias das variaveis
# qtd de ocorrencia de cada uma das categorias
# ------------------------------------------
print(df["TRANSPORTE"].unique())
df["TRANSPORTE"].value_counts()

['motorbike' 'bicycle' 'car' 'neither' 'cargo_van' 'motorbike_trailer']


motorbike            70864
bicycle              55541
car                  33085
neither                 77
cargo_van                7
motorbike_trailer        2
Name: TRANSPORTE, dtype: int64

In [17]:
# ------------------------------------------
# substituicao de cargo_van, motorbike_trailer e neither por motorbike
# ------------------------------------------
df["TRANSPORTE"].replace({
    "neither" : "motorbike",
    "cargo_van" : "motorbike",
    "motorbike_trailer" : "motorbike"
}, inplace=True) 

In [18]:
# ------------------------------------------
# substituicao de dados categoricos por numericos
# ------------------------------------------
df["TRANSPORTE"].replace({
    "motorbike" : 1,
    "bicycle" : 2,
    "car" : 3
}, inplace=True) 

In [19]:
# ------------------------------------------
# CHECAGEM DO TRATAMENTO DA FEATURE
# ------------------------------------------
print(df["TRANSPORTE"].unique())
df["TRANSPORTE"].value_counts()

[1 2 3]


1    70950
2    55541
3    33085
Name: TRANSPORTE, dtype: int64

In [20]:
# ------------------------------------------
# FEATURE : AUTO_ACEITE
# exibe lista de ocorrencias das variaveis
# qtd de ocorrencia de cada uma das categorias
# ------------------------------------------
print(df["AUTO_ACEITE"].unique())
df["AUTO_ACEITE"].value_counts(normalize = True)

[True False nan]


True     0.614867
False    0.385133
Name: AUTO_ACEITE, dtype: float64

In [21]:
# ------------------------------------------
# couriers com auto_aceite == nan deram churn definitivo
# CONCLUSAO : preencher nan com False
# ------------------------------------------
df[df["AUTO_ACEITE"].isnull()]["IS_ACTIVE"].value_counts()
df["AUTO_ACEITE"].fillna(False, inplace=True)

In [22]:
# ------------------------------------------
# substituicao de dados categoricos por numericos
# ------------------------------------------
df["AUTO_ACEITE"].replace({
    True : 1,
    False : 0
}, inplace=True) 

In [23]:
# ------------------------------------------
# CHECAGEM DO TRATAMENTO DA FEATURE
# ------------------------------------------
print(df["AUTO_ACEITE"].unique())
df["AUTO_ACEITE"].value_counts()

[1 0]


1    86395
0    73181
Name: AUTO_ACEITE, dtype: int64

In [24]:
# ------------------------------------------
# FEATURE : COUNT_ORDERS_LAST_7D
# exibe lista de ocorrencias das variaveis
# qtd de ocorrencia de cada uma das categorias
# ------------------------------------------
df["COUNT_ORDERS_LAST_7D"].value_counts(normalize = True)

0.0      0.872951
1.0      0.014814
2.0      0.009563
3.0      0.007489
4.0      0.006110
           ...   
353.0    0.000006
166.0    0.000006
177.0    0.000006
195.0    0.000006
188.0    0.000006
Name: COUNT_ORDERS_LAST_7D, Length: 211, dtype: float64

In [25]:
# ------------------------------------------
# maximo de entregas em uma semana
# ------------------------------------------
df["COUNT_ORDERS_LAST_7D"].max()

353.0

In [26]:
# ------------------------------------------
# segmentacao em buckets
# ------------------------------------------
max = df["COUNT_ORDERS_LAST_7D"].max()
bins = pd.IntervalIndex.from_tuples([(-1, 0.99), (0.99, max * 0.05), (max * 0.05, max * 0.1), (max * 0.10, max * 0.25), (max * 0.25, max)])
df['binned'] = pd.cut(df["COUNT_ORDERS_LAST_7D"], bins)
df['binned'].value_counts()

(-1.0, 0.99]                                139302
(0.99, 17.650000000000002]                   12628
(17.650000000000002, 35.300000000000004]      3889
(35.300000000000004, 88.25]                   3170
(88.25, 353.0]                                 587
Name: binned, dtype: int64

In [27]:
# ------------------------------------------
# CHECAGEM DO TRATAMENTO DA FEATURE
# ------------------------------------------

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159576 entries, 0 to 159575
Data columns (total 48 columns):
 #   Column                          Non-Null Count   Dtype   
---  ------                          --------------   -----   
 0   GENERO                          159576 non-null  int64   
 1   DATA_NASCIMENTO                 159576 non-null  float64 
 2   IS_ACTIVE                       159576 non-null  int64   
 3   TRANSPORTE                      159576 non-null  int64   
 4   AUTO_ACEITE                     159576 non-null  int64   
 5   COUNT_ORDERS_LAST_7D            159576 non-null  float64 
 6   COUNT_ORDERS_LAST_30D           159576 non-null  float64 
 7   COUNT_ORDERS_CANCELED_LAST_7D   159576 non-null  float64 
 8   COUNT_ORDERS_CANCELED_LAST_30D  159576 non-null  float64 
 9   GORJETA                         159576 non-null  float64 
 10  PRIMEIRO_PEDIDO                 140510 non-null  object  
 11  ULTIMO_PEDIDO                   140510 non-null  object  
 12  CO

In [29]:
df.head()

,GENERO,DATA_NASCIMENTO,IS_ACTIVE,TRANSPORTE,AUTO_ACEITE,COUNT_ORDERS_LAST_7D,COUNT_ORDERS_LAST_30D,COUNT_ORDERS_CANCELED_LAST_7D,COUNT_ORDERS_CANCELED_LAST_30D,GORJETA,...,PERMANENT_BLOCK,TEMPORARY_BLOCKS,WARNINGS,DISCIPLINE_INCIDENTS,FRAUD_INCIDENTS,MANUAL_INCIDENTS,PERFORMANCE_INCIDENTS,WARNING_INCIDENTS,ORDERS_PER_SUPPLY_HOURS,binned
0,0,1988.0,1,1,1,1.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(0.99, 17.650000000000002]"
1,0,1998.0,1,1,1,7.0,7.0,0.0,0.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(0.99, 17.650000000000002]"
2,1,1994.0,1,1,1,4.0,4.0,0.0,0.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(0.99, 17.650000000000002]"
3,0,1993.0,1,1,1,2.0,2.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(0.99, 17.650000000000002]"
4,1,2004.0,1,2,1,0.0,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(-1.0, 0.99]"


In [39]:
df["TOTAL_TICKETS"].()

array([ nan,   2.,   3.,   4.,   7.,   1.,   5.,   6.,  14.,  15.,   9.,
        10.,   8.,  23.,  13.,  12.,  24.,  16.,  19.,  11.,  20.,  26.,
        21.,  18.,  25.,  87.,  30.,  22.,  28.,  45.,  31.,  17.,  34.,
        52.,  46.,  59.,  27.,  37.,  41.,  38.,  53.,  42.,  35.,  63.,
        43.,  75.,  32.,  81.,  36.,  29.,  39.,  40.,  33.,  96.,  51.,
        47.,  57.,  62.,  55.,  49.,  73.,  58.,  60.,  56.,  48.,  94.,
       112.,  79.,  78.,  98.,  44.,  50.,  66.,  64., 160.,  68.,  89.,
        83., 102.,  77.,  76.,  95.,  65., 107.,  61.,  82.,  69.,  54.,
        67., 115.,  70.,  93., 119., 103.,  80.,  71., 163., 148.,  99.,
       116.,  72., 100., 120., 104.,  91.,  85.,  84., 145.,  90., 111.,
       165.,  92.,  74., 142., 117., 146., 101., 106., 278., 144., 105.,
       118., 110., 108., 124., 126., 138.,  97., 167., 140., 227., 132.,
        88., 173., 139., 125., 128., 164.])